title: Henri Lefebvre
tagline: Ph.D Student in Mathematical Optimization & casual runner
description: Ph.D Student in Mathematical Optimization at DEI, University of Bologna (Italy) with main interest in Robust Optimization and decomposition methods. Casual runner.
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge