title: hlefebvr
remote_theme: fongandrew/hydeout

# Dependencies
# markdown: redcarpet
# highlighter: pygments

# Setup
tagline: 'just like home'
description: 'Student in Computer Science'
url: http://hlefebvr.github.io
baseurl: /

author:
  name: 'Henri Lefebvre'
  url: http://hlefebvr.github.io

# paginate: 5

# github:
#   repo: https://github.com/hlefebvr

# sidebar_home_link: true