# Open methodology for "Wait-and-see follower"

```{r echo=FALSE, warning=FALSE}
library(rmarkdown)
library(kableExtra)
library(ggplot2)
library(stringr)
suppressPackageStartupMessages(library(dplyr))
```

```{r}
results = read.csv("results.csv", header = FALSE)
colnames(results) = c("tag", "instance", "n_customers", "n_facilities", "Gamma", "follower_type", "use_padm", "total_time", "status", "reason", "best_bound", "best_obj", "n_iterations", "n_scenarios", "master_time", "separation_time")
#results = results %>% mutate(instance = basename(instance))
#results$tag = NULL
results = results %>% mutate(total_time = ifelse(total_time > 7200, 7200, total_time))
#matches = str_match(results$instance, "instance_(\\d+)_(\\d+)_(\\d+)_\\d+\\.txt")
#results = data.frame(
#  results,
#  n_facilites = as.numeric(matches[,2]),
#  n_customers = as.numeric(matches[,3]),
#  ratio = as.numeric(matches[,4]) / 100
#)
results$use_padm = as.logical(results$use_padm)
results$size = paste0(results$n_facilities, ", ", results$n_customers)
paged_table(results)
```

```{r}
ggplot(results, aes(x = total_time, color = use_padm)) +
  stat_ecdf(geom = "step", linewidth = 1) +
  labs(title = "ECDF of Total Time",
       x = "Total Time",
       y = "ECDF") +
  facet_wrap(follower_type~Gamma) +
  theme_minimal()

ggplot(results, aes(x = n_scenarios, color = use_padm)) +
  stat_ecdf(geom = "step", linewidth = 1) +
  labs(title = "ECDF of Scenarios",
       x = "Total Time",
       y = "ECDF") +
  facet_wrap(follower_type~Gamma) +
  theme_minimal()

ggplot(results, aes(x = total_time, color = size)) +
  stat_ecdf(geom = "step", linewidth = 1) +
  labs(title = "ECDF of Total Time",
       x = "Total Time",
       y = "ECDF") +
  facet_wrap(follower_type~Gamma) +
  theme_minimal()
```


## Summary Table 

```{r}
summary_table = results %>%
  filter(total_time < 7200) %>%
  group_by(follower_type, use_padm, n_facilities, n_customers, Gamma) %>%
  summarise(
    n_solved = n(),
    avg_total_time = mean(total_time, na.rm = TRUE),
    avg_master_time = mean(master_time, na.rm = TRUE),
    avg_separation_time = mean(separation_time, na.rm = TRUE),
    avg_n_scenarios = mean(n_scenarios, na.rm = TRUE),
    n_optimal = sum(status == "Optimal"),
    statuses = toString(unique(status)),
    .groups = "drop"
  )

knitr::kable(
    summary_table,
    digits = c(0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0),
    booktabs = TRUE,
    longtable = TRUE,
    col.names = c("Follower", "PADM", "$\\vert V_1 \\vert$", 
      "$\\vert V_2 \\vert$",  "$\\Gamma$", "Solved", "Total Time", 
      "Master Time", "Separation Time", "# Scenarios", "Optimal", "Statuses"),
    caption = "Summary table"
  ) %>%
  kable_classic(latex_options = "hold_position") %>%
  add_header_above(c(" " = 5, "Solved Instances" = 5, "Status Info" = 2))
```
